### ISSUE TITLE
Eating a mooncake kicks the player from dedicated server

### ISSUE THREAD

**Issue by Not-February** [davidjjung/copperpot#7]
Ate a mooncake in the Overworld, got kicked with the message "Internal Server Error"; couldn't tell if you if it'd kick other people too, as I was the only one online at the time. It does this regardless of whether you eat it during the day or at nighttime.

I was able to connect again following this, though my mooncake was gone and didn't seem to give me any of its effects(it did take long enough to log in because of other factors that it may have just worn off before I got in-game, though).

This isn't the full mod list but the versions of mods that I assume would matter most for initial testing purposes based on the food's dependencies; I can provide a full mod list if the issue can't be narrowed down with just this:

``Forge 36.2.0``
``Abnormals Core 3.2.0``
``Bayou Blues 1.0.5``
``Farmer's Delight 0.4.5``
``Copper Pot 1.1.2``
``Neapolitan 2.1.0``

Here is the full server log if you want it(warning, it's long): https://gist.github.com/Febilian/5da4eb252640ab3ca14a9b01a5ee7346

But this is probably the relevant part:

```[08Aug2021 15:54:32.324] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /67.166.92.231:61899
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.World.func_242414_af()I
	at com.davigj.copperpot.common.items.Mooncake.moonlight(Mooncake.java:47) ~[copperpot:1.1.2]
	at com.davigj.copperpot.common.items.Mooncake.func_77654_b(Mooncake.java:32) ~[copperpot:1.1.2]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:221) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1057) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	... 9 more```

**Comment by davidjjung** [comment]
Uhh my kneejerk reaction is to have No idea what may be causing this, but rest assured I will look into it as best as I can!

**Comment by Not-February** [comment]
I also have an additional suggestion/request in regards to the note in your documentation about it being a bad idea to eat in dimensions with 'intentional game design'; perhaps you could have mooncakes not provide effects in other dimensions unless they are specifically whitelisted through a config(so pack devs could add mod dimensions that have moon phases to it)? Or you could have it actually harm the player if they try to eat it in dimensions without a moon(like, apply Instant Harming or another negative on consumption haha).

**Comment by davidjjung** [comment]
ah, that's a great point! it's currently set to have adverse effects when consumed in places without the ability to sleep, but I realize that may be different from dimensions in which there's a moon. I'll try and implement a config for that in the next update, thanks!

**Comment by Sgale952** [comment]
Why is the problem closed? Mooncake is still kicking the player from the server(

**Comment by davidjjung** [comment]
Oh dear
